### ISSUE TITLE
[Feature Request]: Group Playlists into separate Seasons

### ISSUE THREAD

**Issue by SSj-Saturn** [tubearchivist/tubearchivist-plex#87]
### I've read the documentation.

- [X] I have read the [current limitations](https://github.com/tubearchivist/tubearchivist-plex#limitations), and confirmed that this hasn't been requested as a [feature request](https://github.com/tubearchivist/tubearchivist-plex/issues?q=is%3Aissue) previously.

## Is your feature request related to a problem? Please describe.
My main issue is that Youtube channels that have multiple series or playlists are grouped together under the same creator. So while I have them separate under TA as playlist subscriptions, in Plex it gets messy.

eg.
https://www.youtube.com/@GLITCH/playlists

I have subscriptions for both Murder Droids and The Amazing Digital Circus within TA, but within Plex these are just jumbled into the GLITCH channel by release date.

## Describe the solution you'd like
Any possibility to have these separated into Seasons? The current Seasons implementation (by year) isn't very useful overall (unless it's a channel that uploads FREQUENTLY), but it would be great if there's a way to split them up by Seasons or some other way vs the current method.
<img width="1379" alt="Screenshot 2024-12-19 at 6 13 36 PM" src="https://github.com/user-attachments/assets/2271429c-ce02-4bad-97bb-7015391f1736" />

### Your help is needed!

- [ ] Yes, I will work on this in the next few days or weeks.

**Comment by lamusmaser** [comment]
This is similar to #38, which is already in consideration and being developed.

At a high level, we cannot replace the Seasons mechanism. Because of how Plex handles Seasons natively, we cannot create a non-numerical reference for those seasons. Additionally, a YouTube Playlist crosses channels, then it would not be referenceable by Plex, either. As such, the best solution is to import the YT Playlists as native Plex Playlists.
